### ISSUE TITLE
API keys are not used

### ISSUE THREAD

**Issue by jniedrauer** [sfreiberg/gotwilio#38]
Basic auth is hardcoded to use account SID and auth token. API keys can be set but they are ignored. You also can't pass in API keys as the account SID and auth token because the account SID is used to generate the URL for API requests.

**Comment by jniedrauer** [comment]
https://github.com/sfreiberg/gotwilio/pull/39

**Comment by sfreiberg** [comment]
Thanks for the bug report and PR! It's been merged.
