### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by happilymarrieddad** [sfreiberg/gotwilio#46]
Hey,

It works great locally but when I deploy to my Kubernetes cluster I get the following error.
`Post https://api.twilio.com/2010-04-01/Accounts/AC6ce4211566726873dad7c9924ba2ff1c/Messages.json: x509: certificate signed by unknown authority`

I'm pretty sure my cert is valid. We're a decent sized company and we've been using these certs and renewing them for 4 years. This is the first time I've seen this kind of error with twilio. The only difference is we've been moving our API service from NodeJS to Go. Thanks!

![Selection_238](https://user-images.githubusercontent.com/6416323/55023943-757f3a00-4fc3-11e9-8839-242bac66d823.png)
![unnamed (1)](https://user-images.githubusercontent.com/6416323/55023966-816afc00-4fc3-11e9-8860-bd4a5e7a2050.jpg)

**Comment by jniedrauer** [comment]
Sounds to me like your docker images don't have a default root CA bundle. Is there anything at /etc/ssl or /etc/pki/tls? For alpine linux, you need to create your own bundle or `apk add --update ca-certificates` for the public bundle (which will include api.twilio.com)

**Comment by happilymarrieddad** [comment]
@jniedrauer yep, that worked! Thanks!!

**Comment by shubhamdixit863** [comment]
I had same issue with docker deployment ,in ubuntu image .I was using go ,so i just changed my Dockerfile with this

FROM ubuntu:latest

RUN apt-get update
RUN apt-get install ca-certificates -y
RUN  update-ca-certificates

[See this](url) [](https://askubuntu.com/questions/792354/ubuntu-docker-container-update-ca-certificates-command-not-found)
