### ISSUE TITLE
MMS with Copilot?

### ISSUE THREAD

**Issue by wilkesybear** [sfreiberg/gotwilio#68]
Hello!

I see that there was a previous PR https://github.com/sfreiberg/gotwilio/pull/44 that added functionality for MMS with Copilot, along with a `LookupPhone` function, but was ultimately closed. I am in need of MMS usage over Copilot, and would like to add just the `SendMMSWithCopilot` function that was proposed as part of the PR above. Please let me know if there's any more context here about that decision; otherwise, look out for a PR from me coming soon!

Thank you, Andrew

**Comment by sfreiberg** [comment]
Fixed in #69.
